In [1]:
import torch

print(torch.__version__)

2.6.0+cpu


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Get & Set default tensory data type

In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

In [5]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

# Creating tensors

In [6]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]], device=device) 
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
tensor_arr.dtype

torch.float64

In [8]:
torch.is_tensor(tensor_arr)

True

In [9]:
l = [[1,2,3],[4,5,6]]
torch.is_tensor(l)

False

In [10]:
torch.numel(tensor_arr)

6

In [11]:
tensor_arr.shape

torch.Size([2, 3])

In [12]:
tensor_uninitialized = torch.Tensor(2,3, device=device)
tensor_uninitialized

tensor([[1.4934e-311,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [13]:
torch_initialized = torch.rand(2,3, device=device)
torch_initialized

tensor([[0.6647, 0.3115, 0.4445],
        [0.6013, 0.6425, 0.4776]])

In [14]:
torch_int = torch.rand(2,3,device=device).type(torch.int32)
torch_int

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [15]:
torch_int = torch.randint(0, 100, (2, 3), device=device, dtype = torch.int32)
torch_int

tensor([[29, 46, 98],
        [55, 74, 84]], dtype=torch.int32)

In [16]:
torch_fill = torch.full((2,3), fill_value=5, device=device)
torch_fill

tensor([[5, 5, 5],
        [5, 5, 5]])

In [17]:
torch_ones = torch.ones((2,3), device=device)
torch_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch_zeroes = torch.zeros((2,3), device=device)
torch_zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch_zeroes = torch.zeros_like(tensor_arr, device=device)
torch_zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Creating a tensor representing an identity matrix

In [20]:
torch_identity_matrix = torch.eye(7, device=device)
torch_identity_matrix

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
torch.nonzero(torch_identity_matrix)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]])

## Creating a sparce tensor

In [22]:
indices = torch.tensor([[0, 1, 2], [1, 2, 3]])
values = torch.tensor([7, 11, 21])
sparse_tensor = torch.sparse_coo_tensor(indices, values, (4, 4), device=device)
print("Indices of sparse tensor:")
print(indices)

print("\nValues of sparse tensor:")
print(values)

print("\nSparse tensor:")
print(sparse_tensor)

print("\nDense representation of sparse tensor:")
print(sparse_tensor.to_dense())

Indices of sparse tensor:
tensor([[0, 1, 2],
        [1, 2, 3]])

Values of sparse tensor:
tensor([ 7, 11, 21])

Sparse tensor:
tensor(indices=tensor([[0, 1, 2],
                       [1, 2, 3]]),
       values=tensor([ 7, 11, 21]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo)

Dense representation of sparse tensor:
tensor([[ 0,  7,  0,  0],
        [ 0,  0, 11,  0],
        [ 0,  0,  0, 21],
        [ 0,  0,  0,  0]])


## Creating tensors with evenly spaced numbers

In [23]:
x = torch.linspace(0, 10, steps=20, device=device)
x

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

# In-Place & Out of Place operations on tensors

In [24]:
initial_tensor = torch.rand(2, 3, device=device)
initial_tensor.fill_(5)
initial_tensor

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [25]:
initial_tensor.add(10)

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [26]:
initial_tensor

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [27]:
initial_tensor.add_(10)

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [28]:
initial_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [29]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [30]:
initial_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [31]:
initial_tensor.sqrt_()
initial_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [32]:
initial_tensor.transpose_(0,1)
initial_tensor

tensor([[3.8730, 3.8730],
        [3.8730, 3.8730],
        [3.8730, 3.8730]])

In [33]:
x = torch.linspace(0, 10, steps=15, device=device).reshape(3, 5)
x

tensor([[ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571],
        [ 3.5714,  4.2857,  5.0000,  5.7143,  6.4286],
        [ 7.1429,  7.8571,  8.5714,  9.2857, 10.0000]])

In [34]:
tensor_chunk = torch.chunk(x, 5, dim=1)
tensor_chunk


(tensor([[0.0000],
         [3.5714],
         [7.1429]]),
 tensor([[0.7143],
         [4.2857],
         [7.8571]]),
 tensor([[1.4286],
         [5.0000],
         [8.5714]]),
 tensor([[2.1429],
         [5.7143],
         [9.2857]]),
 tensor([[ 2.8571],
         [ 6.4286],
         [10.0000]]))

In [35]:
tensor_concatenated = torch.cat(tensor_chunk, dim=1)
tensor_concatenated

tensor([[ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571],
        [ 3.5714,  4.2857,  5.0000,  5.7143,  6.4286],
        [ 7.1429,  7.8571,  8.5714,  9.2857, 10.0000]])

In [36]:
tensor_chunk[0].shape

torch.Size([3, 1])

In [37]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([[1],[2]], device=device)

tensor_concatenated = torch.cat((tensor1, tensor2, tensor3), 0)
tensor_concatenated

tensor([[0.0000],
        [3.5714],
        [7.1429],
        [0.7143],
        [4.2857],
        [7.8571],
        [1.0000],
        [2.0000]])

In [38]:
initial_tensor.shape

torch.Size([3, 2])

In [39]:
unsqueezed_tensor = torch.unsqueeze(initial_tensor, 1)
unsqueezed_tensor.shape, unsqueezed_tensor

(torch.Size([3, 1, 2]),
 tensor([[[3.8730, 3.8730]],
 
         [[3.8730, 3.8730]],
 
         [[3.8730, 3.8730]]]))

In [40]:
squeezed_tensor = torch.squeeze(unsqueezed_tensor, 1)
squeezed_tensor.shape, squeezed_tensor

(torch.Size([3, 2]),
 tensor([[3.8730, 3.8730],
         [3.8730, 3.8730],
         [3.8730, 3.8730]]))

In [41]:
import numpy as np
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 
B.shape

(4, 1)